### ISSUE TITLE
Currently the app is not compatible with Kodi 19

### ISSUE THREAD

**Issue by Wikinaut** [Oderik/xbmc-somafm#13]

**Comment by gordielachance** [comment]
We love this addon ! Please update it :D

**Comment by Oderik** [comment]
@Wikinaut @gordielachance hey guys!

Sorry to tell you that I don't maintain this any more (as you probably have guessed already 😉). 

As you can see I forked this repository from https://github.com/nils-werner/xbmc-somafm a couple of years ago when it was in a similar situation. I then took over to make it usable again. So now, I hope someone else is willing to take over.

I don't remember the exact details of how to get the add on integrated into the official Kodi add on repository, but back then I think it involved participating in a mailing list and propagating updates of the add on there. The code would later be fetched from this repository.

So, the next maintainer needs to takte these steps:

- [ ] fork this repository (or see below)
- [ ] fix the add on
- [ ] do what's necessary to make that new version the official add on

To make any maintainer transition easier in the future, maybe it's a good idea to move this repository (including the issues and so on) to an organization that is dedicated to the Soma FM Kodi Add On. I can help with that if desired by the next maintainer. I don't know it would really be necessary, but at least it wouldn't look like I was still working on this while someone else is doing the actual work. 😅

Please feel free to contact me if you feel that you are... **the next maintainer of this add on!**

**Comment by Oderik** [comment]
@PanderMusubi what about you?

**Comment by makepanic** [comment]
I created https://github.com/Oderik/xbmc-somafm/pull/14 which makes this great addon work again on kodi@19.
Would be nice if any of you can test or review the changes :)

**Comment by inverse** [comment]
@makepanic any steps to testing this out? Change seem legit :)

**Comment by makepanic** [comment]
> @makepanic any steps to testing this out? I've never worked with Kodi on the development side. Change seem legit though :)

I think you could download my PR and zip it. Then install it on kodi via zip.

The zipfile should be called `plugin.audio.somafm.zip` and contain all the source in a folder called `plugin.audio.somafm`:

```
unzip -l plugin.audio.somafm.zip
Archive:  plugin.audio.somafm.zip
  Length      Date    Time    Name
---------  ---------- -----   ----
        0  08-10-2021 21:21   plugin.audio.somafm/
        6  08-10-2021 18:52   plugin.audio.somafm/.gitignore
    15230  08-10-2021 18:52   plugin.audio.somafm/LICENSE.txt
     1436  08-10-2021 18:52   plugin.audio.somafm/README.md
```

I'm already using it on my osmc installation for a couple weeks and it seems to work just fine.

**Comment by inverse** [comment]
![image](https://user-images.githubusercontent.com/713525/130593651-bb2c452f-a098-4261-a9c8-d1fa8734ad7f.png)

Success - was more painful then expected having to get a Ubuntu VM up to install kodi and then copy the file.

Does the Kodi team not provide a development setup for this to run stuff unpacked etc?

**Comment by makepanic** [comment]
> Does the Kodi team not provide a development setup for this to run stuff unpacked etc?
> what was your dev flow like working on this?

I installed kodi locally, enabled logging and cloned the repository.
Then i could simply symlink the addon to `~/.kodi/addons` and check the logfile in `~/.kodi/temp/kodi.log` for errors.

Before running it i opened it in intellij to fix general python 2 -> 3 issues which were only some print and urllib import issues.

Afterwards i ran the addon inside kodi and tried to figure out where it crashed. Then cross referencing the [kodi python api](https://codedocs.xyz/AlwinEsch/kodi/group__python__xbmcgui__listitem.html#ga15bcb930a4f91dd97f8ed7c633a20618) and the [python api changes thread](https://forum.kodi.tv/showthread.php?tid=344263) it was kinda easy to adjust it to use the new api.

The biggest hurdles was me not using python in years and never touching kodi addons 😅

**Comment by inverse** [comment]
@makepanic Is this documented anywhere on their site/wiki? even as a `CONTRIBUTING.md` file within this repo. 

Thanks for the write up. It's much appreciated 🙏🏼

**Comment by makepanic** [comment]
might be somewhere in https://kodi.wiki/view/Add-on_development

**Comment by evinr** [comment]
> @Wikinaut @gordielachance hey guys!
> 
> Sorry to tell you that I don't maintain this any more (as you probably have guessed already wink).
> 
> As you can see I forked this repository from https://github.com/nils-werner/xbmc-somafm a couple of years ago when it was in a similar situation. I then took over to make it usable again. So now, I hope someone else is willing to take over.
> 
> I don't remember the exact details of how to get the add on integrated into the official Kodi add on repository, but back then I think it involved participating in a mailing list and propagating updates of the add on there. The code would later be fetched from this repository.
> 
> So, the next maintainer needs to takte these steps:
> 
>     * [ ]  fork this repository (or see below)
> 
>     * [ ]  fix the add on
> 
>     * [ ]  do what's necessary to make that new version the official add on
> 
> 
> To make any maintainer transition easier in the future, maybe it's a good idea to move this repository (including the issues and so on) to an organization that is dedicated to the Soma FM Kodi Add On. I can help with that if desired by the next maintainer. The ownership of that organization can then be passed from maintainer to maintainer (or just add any maintainer as an owner). I don't know it would really be necessary, but at least it wouldn't look like I was still working on this while someone else is doing the actual work. sweat_smile
> 
> Please feel free to contact me if you feel that you are... **the next maintainer of this add on!**
> 
> Pro tip: listen to Soma FM while working on the add on. ;)

Ask and you shall receive :)
https://github.com/Soma-FM-Kodi-Add-On

With your blessing I will update the addon.xml to reflect recent changes and then pursue getting the v19+ fix version publicly available.

**Comment by Oderik** [comment]
Of course, please go ahead! And thank you for getting it done!

**Comment by evinr** [comment]
@Oderik and others, I believe I have completed the migration to the new organization and repo. Let me know if there is anything else that I missed or setup wrong. The new space can be found here: 
https://github.com/Soma-FM-Kodi-Add-On/plugin.audio.somafm

I have merged @makepanic and my changes on that repo that will be submitted for review. I tagged the latest at v2.0.0. 

Thanks for making this very smooth! If anyone is interested in joining the new organization I can always use help with QA and requirement wrangling. I will update this thread as the situation progresses.

**Comment by inverse** [comment]
@evinr thanks for taking this 🙏🏼

**Comment by evinr** [comment]
PR for getting it mainlined to v19: https://github.com/xbmc/repo-plugins/pull/3786

**Comment by pewkodi** [comment]
@evinr  @Oderik  @inverse I have a working version based on your code in kodi 19 as well since I am trying to migrate to kodi 19. I noticed the getfilepath function is now getPath. I was scratching my head on that one and used re and strip. 

I did modify the path translate function in my code since it is going away.
[somafm_workingkodi19v2.zip](https://github.com/Oderik/xbmc-somafm/files/7644530/somafm_workingkodi19v2.zip)

**Comment by evinr** [comment]
Fifth time is the charm! https://github.com/xbmc/repo-plugins/pull/3831#event-5835067336

Version 2.0.1 is live and installable via the Install from Repository option!!! 

Huge shoutout to @makepanic @inverse and @Oderik for getting the code migrated and  deployed!

**Comment by inverse** [comment]
Thanks so much for your hard work @evinr 🙏🏼 

Just installed it on coreELEC and works perfectly
